services:
  qq-farm-bot:
    image: qq-farm-bot-ui-better
    build:
      context: .
      dockerfile: apps/core/Dockerfile
    container_name: core
    restart: unless-stopped
    environment:
      ADMIN_PASSWORD: admin
      TZ: Asia/Shanghai
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/core/data
